project_id     = "todo-api-cloudrun"
region         = "asia-northeast2"
container_image = "gcr.io/todo-api-cloudrun/todo-api:latest"
db_password    = "postgres_password"
db_host        = "131.186.56.105"
db_port        = "5432"
db_name        = "postgres_db"
db_user        = "postgres"
